version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: codeinwp/themeisle-sdk
    versions:
    - 3.2.16
    - 3.2.18
    - 3.2.19
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
